name: Coverage Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    container: 
      image: golang:1.23

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests with coverage
        run: go test ./... -coverprofile=coverage.out -covermode=atomic

      - name: Check coverage threshold
        run: |
          COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
          echo "Coverage: $COVERAGE%"
          if (( $(echo "$COVERAGE < 85.0" | bc -l) )); then
            echo "Coverage is below 85%! Failing the job."
            exit 1
          fi

      - name: Build project
        run: go build
